### ISSUE TITLE
Проблемы с запуском

### ISSUE THREAD

**Issue by gotlium** [smi2/clickhouse-frontend#10]
```
$ gulp serve

/opt/clickhouse-frontend/node_modules/gulp-favicons/index.js:2
(() => {
  ^
SyntaxError: Unexpected token )
    at Module._compile (module.js:439:25)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/opt/clickhouse-frontend/gulp/favicon.js:1:78)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
```

не удается нормально запустить. 

```
$ nodejs --version
v0.10.47
```

Ubuntu 14.04

**Comment by gotlium** [comment]
Обновил nodejs до последней версии. Запуск прошел успешно.

**Comment by isublimity** [comment]
Спасибо, добавил в readme - что нужна последнии версии 

Мы используем http://guiclickhouse.smi2.ru т/к он чисто "клиентски", и ставим node только если необходима разработка клиента

**Comment by gotlium** [comment]
так же поставил последнюю версию CH. так как с этим так же была проблема.
получил дополнительно ошибку при `;` в конце sql выражения. после лишь понял что доставляется формат.
